#pragma once

// Blend modes
#define MATERIAL_BLEND_MODE_OPAQUE 0
#define MATERIAL_BLEND_MODE_ALPHA_MASKED 1
#define MATERIAL_BLEND_MODE_TRANSLUCENT 2

#ifndef MATERIAL_BLEND_MODE
#define MATERIAL_BLEND_MODE	MATERIAL_BLEND_MODE_OPAQUE
#endif

#ifndef MATERIAL_IS_DOUBLE_SIDED
#define MATERIAL_IS_DOUBLE_SIDED 0
#endif